---
- name: Include variables
  include_vars: "chrony_{{ ansible_facts['os_family'] | lower }}.yml"

- name: Install packages
  ansible.builtin.package:
    name: "{{ chrony_packages }}"
    state: present

- name: Fix permissions for chrony home directory
  ansible.builtin.file:
    path: "{{ chrony_homedir }}"
    state: directory
    mode: 0750

- name: Deploy configuration
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_file }}"
    owner: "{{ chrony_owner }}"
    group: "{{ chrony_group }}"
    mode: "{{ chrony_mode }}"
  notify: "chrony service restart"

- name: Manage the state of service
  ansible.builtin.systemd:
    name: "{{ chrony_service_name }}"
    state: started
    enabled: true
