---
# https://github.com/ansible/ansible-lint-action
name: Ansible Lint

on: push

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Lint Ansible roles
        uses: ansible/ansible-lint-action@master
